graph _build-path {
  meta: { description: "Build a relative path with _folderPath prefix, stores result in _resolvedPath", type: "core", input: "_pathFileName, _folderPath", output: "_resolvedPath" }

  let getFileName = get(key: "_pathFileName")
  let getFolderPath = get(key: "_folderPath")
  let pathNil = isNil(value: "{{getFolderPath}}")
  let buildPath = if pathNil {
    let rootPath = concat(a: "folders/", b: "{{getFileName}}")
    let setPath = set(key: "_resolvedPath", value: "{{rootPath}}")
  } else {
    let subPath = concat(a: "folders/", b: "{{getFolderPath}}")
    let fullPath = concat(a: "{{subPath}}", b: "/")
    let filePath = concat(a: "{{fullPath}}", b: "{{getFileName}}")
    let setPath = set(key: "_resolvedPath", value: "{{filePath}}")
  }
}