graph handle-new-file {
  meta: { description: "Create a new text file via shared graph", type: "core", input: "_folderNewCounter", output: "_itemName, _itemContent" }

  let hideMenu = execFile(file: "ui/components/context-menu/hide")
  let nextCount = execFile(file: "ui/views/folder/_next-counter")
  let getCurrent = get(key: "_folderNewCounter")
  let fileName = concat(a: "New File ", b: "{{getCurrent}}")
  let getFolderPath = get(key: "_folderPath")
  let createFile = execFile(file: "ui/views/folder/_create-file", store: { _itemName: "{{fileName}}", _itemContent: "", _folderPath: "{{getFolderPath}}" }, isolated: true)
  let refreshView = execFile(file: "ui/views/folder/create")
}