graph handle-new-folder {
  meta: { description: "Create a new folder via shared graph", type: "core", input: "_folderNewCounter", output: "_itemName" }

  let hideMenu = execFile(file: "ui/components/context-menu/hide")
  let nextCount = execFile(file: "ui/views/folder/_next-counter")
  let getCurrent = get(key: "_folderNewCounter")
  let folderName = concat(a: "New Folder ", b: "{{getCurrent}}")
  let getFolderPath = get(key: "_folderPath")
  let createFolder = execFile(file: "ui/views/folder/_create-folder", store: { _itemName: "{{folderName}}", _folderPath: "{{getFolderPath}}" }, isolated: true)
  let refreshView = execFile(file: "ui/views/folder/create")
}