graph handle-delete {
  meta: { description: "Delete a folder or file via shared graph", type: "core", input: "_ctxItemIndex, _folderItems", output: "_itemName, _itemType" }

  let getIndex = get(key: "_ctxItemIndex")
  let getIndexNum = toNum(value: "{{getIndex}}")
  let getItems = get(key: "_folderItems")
  let getItem = getAt(array: "{{getItems}}", index: "{{getIndexNum}}")
  let getItemName = getProp(obj: "{{getItem}}", key: "name")
  let getItemType = getProp(obj: "{{getItem}}", key: "type")
  let setType = set(key: "_itemType", value: "{{getItemType}}")
  let getFolderPath = get(key: "_folderPath")
  let deleteItem = execFile(file: "ui/views/folder/_delete-item", store: { _itemName: "{{getItemName}}", _folderPath: "{{getFolderPath}}" }, isolated: true)
  let refreshView = execFile(file: "ui/views/folder/create")
}