graph update-growth-index {
  meta: { description: "Update growth index file", type: "core", input: "name, __graph_*", output: "growths/index.json" }

  let getName = get(key: "name")
  let buildGraphKey = concat(a: "__graph_", b: "{{getName}}")
  let getGraph = get(key: "{{buildGraphKey}}")
  let getGraphMeta = getProp(obj: "{{getGraph}}", key: "_meta")
  let getType = getProp(obj: "{{getGraphMeta}}", key: "type")
  let getIcon = getProp(obj: "{{getGraphMeta}}", key: "icon")
  let getDesc = getProp(obj: "{{getGraphMeta}}", key: "description")
  let getGraphInput = getProp(obj: "{{getGraph}}", key: "interface")
  let getGraphOutputRef = getProp(obj: "{{getGraph}}", key: "outputRef")
  let filePath = concat(a: "growths/", b: "{{getName}}")
  let filePathAcs = concat(a: "{{filePath}}", b: "/main.acs")
  let readIndex = readLocal(key: "growths/index.json")
  let indexIsArray = isArr(value: "{{readIndex}}")
  let initIndex = if indexIsArray {
    let keepIndex = set(key: "_growthIndex", value: "{{readIndex}}")
  } else {
    let newIndex = set(key: "_growthIndex", value: [])
  }
  let getIndex = get(key: "_growthIndex")
  let filterExisting = filter item in getIndex {
    let getItemName = getProp(obj: "{{item}}", key: "name")
    let isSame = eq(a: "{{getItemName}}", b: "{{getName}}")
    let isNotSame = not(value: "{{isSame}}")
  }
  let setEntry = set(key: "_growthEntry", value: { name: "{{getName}}", path: "{{filePathAcs}}", type: "{{getType}}", icon: "{{getIcon}}", description: "{{getDesc}}", input: "{{getGraphInput}}", output: "{{getGraphOutputRef}}", locked: false })
  let pushEntry = push(array: "{{filterExisting}}", value: "{{setEntry}}")
  let saveIndex = writeLocal(key: "growths/index.json", value: "{{pushEntry}}")
}
