graph add-model {
  meta: { description: "Add AI model", type: "core", input: "newModelInput, _providersMap, aiModelsList", output: "aiModelsList, addedModel, newModel" }

  let getInput = get(key: "newModelInput")
  let getInputName = getProp(obj: "{{getInput}}", key: "name")
  let getInputProvider = getProp(obj: "{{getInput}}", key: "provider")
  let getInputModelName = getProp(obj: "{{getInput}}", key: "modelName")
  let getInputApiKey = getProp(obj: "{{getInput}}", key: "apiKey")
  let getInputBaseUrl = getProp(obj: "{{getInput}}", key: "baseUrl")
  let setIdPrefix = set(key: "idPrefix", value: "model")
  let generateId = execFile(file: "models/generate-id")
  let getProvidersMap = get(key: "_providersMap")
  let getProviderInfo = getProp(obj: "{{getProvidersMap}}", key: "{{getInputProvider}}")
  let getProviderLogo = getProp(obj: "{{getProviderInfo}}", key: "logo")
  let createModel = set(key: "newModel", value: { id: "{{generateId}}", name: "{{getInputName}}", provider: "{{getInputProvider}}", modelName: "{{getInputModelName}}", apiKey: "{{getInputApiKey}}", baseUrl: "{{getInputBaseUrl}}", logo: "{{getProviderLogo}}" })
  let loadModels = execFile(file: "models/load-models")
  let getList = get(key: "aiModelsList")
  let checkModels = if getList {
    let push = push(array: "{{getList}}", value: "{{newModel}}")
  } else {
    let createArray = push(array: [], value: "{{newModel}}")
  }
  let setList = set(key: "aiModelsList", value: "{{checkModels}}")
  let saveModels = execFile(file: "models/save-models")
  let setResult = set(key: "addedModel", value: "{{createModel}}")
}