graph submit-add-form {
  meta: { description: "Submit add model form (coordinator)", type: "core", output: "aiModelsList, addedModel" }

  let getFormValues = execFile(file: "models/get-add-model-form-values")
  let addModel = execFile(file: "models/add-model")
  let hideForm = execFile(file: "ui/components/add-model-form/hide")
  let clearMainView = clearElement(id: "mainViewContainer")
  let render = execFile(file: "ui/views/market/create")
}