graph tab-switch {
  meta: { description: "Handle market tab switch click", type: "core", input: "clickTargetId", output: "currentMarketTab" }

  let getTargetId = get(key: "clickTargetId")
  let isModelsTab = eq(a: "{{getTargetId}}", b: "modelsTab")
  let handleTab = if isModelsTab {
    let setModelsTab = setGlobal(key: "currentMarketTab", value: "models")
    let clearMainView = clearElement(id: "mainViewContainer")
    let reRender = execFile(file: "ui/views/market/create")
  } else {
    let setGrowthsTab = setGlobal(key: "currentMarketTab", value: "growths")
    let clearMainView = clearElement(id: "mainViewContainer")
    let reRender = execFile(file: "ui/views/market/create")
  }
}
